using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using MySql.Data.MySqlClient;
using System.IO;

namespace AssetMS
{
    public partial class allQueries : DevExpress.XtraEditors.XtraForm, IChildSave
    {
        string pathToPDF;

        static string conString = "Server=localhost; Database=wpams; Uid=root; Pwd=";
        MySqlConnection conn = new MySqlConnection(conString);

        interface IChildSave
        {
            void SaveAction();
            void reset();
            string Xport(String ext);
            void updatethis();
            void deleteThis();
            void NavigateDown();
            void NavigateUp();
        }
        public allQueries()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
        }

        private void repositoryItemButtonEdit1_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            var rowHandle = gridView1.FocusedRowHandle;

            // Get the value for the given column - convert to the type you're expecting
            var obj = gridView1.GetRowCellValue(rowHandle, "ID");

           string id = obj.ToString();
            DialogResult dlr = DevExpress.XtraEditors.XtraMessageBox.Show("Are you sure you want to remove this query from the list of querries?", "System Confirmation", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
            if (dlr == DialogResult.Yes)
            {
                try
                {
                    conn.Open();
                    using (MySqlCommand command = new MySqlCommand("UPDATE reportedissues SET IssueSolved =@IssueSolved WHERE ID = @ID", conn))
                    {
                        command.Parameters.AddWithValue("@IssueSolved", "TRUE");
                        command.Parameters.AddWithValue("@ID", id);
                        command.ExecuteNonQuery();
                        XtraMessageBox.Show("Query Removed", "Action Successful", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        reset();
                        //  gridControl1.RefreshDataSource();
                    }

                }
                catch (MySqlException es)
                {
                    XtraMessageBox.Show(es.ToString());
                }


            }
            else if (dlr == DialogResult.No)
            {
               // e.Cancel = true;
            }
           
        }

        public void SaveAction()
        {
           // //throw new NotImplementedException();
        }

        public void reset()
        {
            ////throw new NotImplementedException();
            sqlDataSource2.Fill();
        }

        public string Xport(string ext)
        {
            using (SaveFileDialog saveDialog = new SaveFileDialog())
            {
                saveDialog.Filter = ext;
                if (saveDialog.ShowDialog() != DialogResult.Cancel)
                {
                    string exportFilePath = saveDialog.FileName;
                    string fileExtenstion = new FileInfo(exportFilePath).Extension;

                    switch (fileExtenstion)
                    {
                        case ".xls":
                            gridControl1.ExportToXls(exportFilePath);
                            break;
                        case ".xlsx":
                            gridControl1.ExportToXlsx(exportFilePath);
                            break;
                        case ".rtf":
                            gridControl1.ExportToRtf(exportFilePath);
                            break;
                        case ".pdf":
                            gridControl1.ExportToPdf(exportFilePath);
                            break;
                        case ".html":
                            gridControl1.ExportToHtml(exportFilePath);
                            break;
                        case ".mht":
                            gridControl1.ExportToMht(exportFilePath);
                            break;
                        default:
                            break;
                    }

                    if (File.Exists(exportFilePath))
                    {
                        try
                        {
                            //Try to open the file and let windows decide how to open it.
                            // System.Diagnostics.Process.Start(exportFilePath);

                            //string ext = Path.GetExtension(exportFilePath);
                            if (!(fileExtenstion.Equals(".pdf")))
                            {
                                System.Diagnostics.Process.Start(exportFilePath);
                            }
                            else
                            {
                                // MessageBox.Show("pdf detected", "Error!", MessageBoxButtons.OK, MessageBoxIcon.Error);
                                pathToPDF = exportFilePath;

                            }

                            // pdfviewer pf = new pdfviewer();
                            //pf.
                        }
                        catch
                        {
                            String msg = "The file could not be opened." + Environment.NewLine + Environment.NewLine + "Path: " + exportFilePath;
                            XtraMessageBox.Show(msg, "Error!", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                    }
                    else
                    {
                        String msg = "The file could not be saved." + Environment.NewLine + Environment.NewLine + "Path: " + exportFilePath;
                        XtraMessageBox.Show(msg, "Error!", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }
            }

            return pathToPDF;
        }

        public void updatethis()
        {
          //  //throw new NotImplementedException();
        }

        public void deleteThis()
        {
            if (gridView1 == null) return;
            
            gridView1.GetDataRow(gridView1.FocusedRowHandle);
        }

        public void NavigateDown()
        {
            // //throw new NotImplementedException();
            gridView1.MovePrev();
        }

        public void NavigateUp()
        {
            //  //throw new NotImplementedException();
            gridView1.MoveNext();
        }

        private void gridView1_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            var rowHandle = gridView1.FocusedRowHandle;

            // Get the value for the given column - convert to the type you're expecting
            var obj = gridView1.GetRowCellValue(rowHandle, "ID");

          //  MessageBox.Show(obj.ToString());
        }

        private void viewQueryAdmin_Load(object sender, EventArgs e)
        {

        }
    }
}